version: '3.8'
services:
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.17.1'
    container_name: elasticsearch
    ports:
    - '9200:9200'
    - '9300:9300'
    environment:
    - "discovery.type=single-node"
    networks:
    - demo
  kibana:
    container_name: kibana
    image: 'docker.elastic.co/kibana/kibana:7.17.1'
    environment:
    - 'ELASTICSEARCH_HOSTS=http://elasticsearch:9200'
    depends_on:
    - elasticsearch
    networks:
    - demo
    ports:
    - '5601:5601'
  postgres:
    container_name: postgres
    image: postgres:14.5-alpine
    tmpfs: /var/lib/postgresql/data
    ports:
    - "5432:5432"
    networks:
    - demo
    volumes:
    - ./initdb:/docker-entrypoint-initdb.d:Z
    environment:
      POSTGRES_PASSWORD: 'password'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'demo'
  filebeat:
    container_name: filebeat
    image: docker.elastic.co/beats/filebeat:7.17.1
    depends_on:
      - kibana
    volumes:
      - ./filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./metrics:/metrics:Z
    networks:
    - demo

networks:
  demo:
    name: 'demo'
