version: "3.3"
services:
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.17.1'
    container_name: elasticsearch
    ports:
    - '9200:9200'
    - '9300:9300'
    environment:
    - "discovery.type=single-node"
  kibana:
    image: 'docker.elastic.co/kibana/kibana:7.17.1'
    environment:
    - 'ELASTICSEARCH_HOSTS=http://elasticsearch:9200'
    depends_on:
    - elasticsearch
    ports:
    - '5601:5601'
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.17.1
    depends_on:
    - kibana
    volumes:
    - ./filebeat.docker.yml:/usr/share/filebeat/filebeat.yml
    - nginx-logs:/var/log/nginx:Z
  nginx:
    image: nginx:1.23.1
    volumes:
    - nginx-logs:/var/log/nginx:Z
    - ./default.conf:/etc/nginx/conf.d/default.conf:Z
    healthcheck:
      test: ["CMD", "curl", "-fIs", "http://localhost"]
      interval: 30s


volumes:
  nginx-logs:
