version: "3.3"
services:
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.17.24'
    container_name: elasticsearch
    ports:
    - '9200:9200'
    - '9300:9300'
    environment:
    - "discovery.type=single-node"
  kibana:
    image: 'docker.elastic.co/kibana/kibana:7.17.24'
    environment:
    - 'ELASTICSEARCH_HOSTS=http://elasticsearch:9200'
    depends_on:
    - elasticsearch
    ports:
    - '5601:5601'
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.17.1
    depends_on:
    - kibana
    volumes:
    - ./filebeat.docker.yml:/usr/share/filebeat/filebeat.yml
    - nginx-logs:/var/log/nginx
  nginx:
    image: nginx:1.23.1
    volumes:
    - nginx-logs:/var/log/nginx
    - ./default.conf:/etc/nginx/conf.d/default.conf:Z
    - ./nginx.conf:/etc/nginx/nginx.conf:Z
    healthcheck:
      test: ["CMD", "curl", "-fIs", "http://localhost"]
      interval: 30s
  curl-request-client:
    volumes:
      - ./nginx-access-pipeline.json:/nginx-access-pipeline.json:Z
    image: byrnedo/alpine-curl:3.17
    command: [
      "-X", "PUT", "http://elasticsearch:9200/_ingest/pipeline/filebeat-7.17.1-nginx-access-pipeline", "-H", "Content-Type: application/json", "-d", "@nginx-access-pipeline.json"
    ]

volumes:
  nginx-logs:
